// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactNative from "react-native";
import * as Email from "../icons/email";
import * as ReactNativeSvg from "react-native-svg";

var SvgXml = { };

var email = Email.default;

function xmlFromIcon(icon) {
  if (icon === "email") {
    return email;
  }
  
}

function Icon(Props) {
  var icon = Props.icon;
  var size = Props.size;
  var color = Props.color;
  var wrapperStyle = Props.wrapperStyle;
  var match = xmlFromIcon(icon);
  if (match !== undefined) {
    return React.createElement(ReactNative.View, {
                style: ReactNative.StyleSheet.flatten(/* array */[
                      {
                        alignItems: "center",
                        display: "flex",
                        height: size,
                        justifyContent: "center",
                        width: size
                      },
                      wrapperStyle
                    ]),
                children: React.createElement(ReactNativeSvg.SvgXml, {
                      xml: match,
                      override: {
                        width: size,
                        height: size,
                        fill: color
                      }
                    })
              });
  } else {
    return null;
  }
}

var make = Icon;

var $$default = Icon;

export {
  SvgXml ,
  email ,
  xmlFromIcon ,
  make ,
  $$default ,
  $$default as default,
  
}
/* email Not a pure module */
