// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as ReactNative from "react-native";
import * as InjectThemeJs from "../helpers/injectTheme.js";

function injectTheme(prim) {
  return InjectThemeJs.default(prim);
}

var isAndroid = ReactNative.Platform.OS === "android";

var isIOS = ReactNative.Platform.OS === "ios";

var Platform = {
  isAndroid: isAndroid,
  isIOS: isIOS
};

export {
  injectTheme ,
  Platform ,
  
}
/* isAndroid Not a pure module */
