// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as ReactNative from "react-native";
import * as InjectThemeJs from "../helpers/injectTheme.js";
import * as ReactNativeSafeAreaView from "react-native-safe-area-view";

function injectTheme(prim) {
  return InjectThemeJs.default(prim);
}

function hasHomeBar(param) {
  var $$window = ReactNative.Dimensions.get("window");
  var isLandscape = $$window.width > $$window.height;
  var bottomPadding = ReactNativeSafeAreaView.getInset("bottom", isLandscape);
  return bottomPadding > 0.0;
}

var isAndroid = ReactNative.Platform.OS === "android";

var isIOS = ReactNative.Platform.OS === "ios";

var Platform = {
  isAndroid: isAndroid,
  isIOS: isIOS
};

export {
  injectTheme ,
  hasHomeBar ,
  Platform ,
  
}
/* isAndroid Not a pure module */
