// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as InjectThemeJs from "../helpers/injectTheme.js";

function injectTheme(prim) {
  return InjectThemeJs.default(prim);
}

export {
  injectTheme ,
  
}
/* ../helpers/injectTheme.js Not a pure module */
