// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as ReactNative from "react-native";
import * as Hero_Variables from "./Hero_Variables.bs.js";

var tmp = {
  color: Hero_Variables._TEXT_COLOR,
  fontSize: Hero_Variables._HEADER_4
};

if (Hero_Variables._FONT_FAMILY !== undefined) {
  tmp.fontFamily = Caml_option.valFromOption(Hero_Variables._FONT_FAMILY);
}

var styles = {
  text: tmp,
  h1: {
    fontSize: Hero_Variables._HEADER_1
  },
  h2: {
    fontSize: Hero_Variables._HEADER_2
  },
  h3: {
    fontSize: Hero_Variables._HEADER_3
  },
  h4: {
    fontSize: Hero_Variables._HEADER_4
  },
  h5: {
    fontSize: Hero_Variables._HEADER_5
  }
};

var $$default = ReactNative.StyleSheet.create(styles);

var _COLOR = Hero_Variables._TEXT_COLOR;

var _FONT_SIZE = Hero_Variables._HEADER_4;

var _H1_FONT_SIZE = Hero_Variables._HEADER_1;

var _H2_FONT_SIZE = Hero_Variables._HEADER_2;

var _H3_FONT_SIZE = Hero_Variables._HEADER_3;

var _H4_FONT_SIZE = Hero_Variables._HEADER_4;

var _H5_FONT_SIZE = Hero_Variables._HEADER_5;

export {
  _COLOR ,
  _FONT_SIZE ,
  _H1_FONT_SIZE ,
  _H2_FONT_SIZE ,
  _H3_FONT_SIZE ,
  _H4_FONT_SIZE ,
  _H5_FONT_SIZE ,
  styles ,
  $$default ,
  $$default as default,
  
}
/* default Not a pure module */
