// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as ReactNative from "react-native";
import * as Hero_Variables from "./Hero_Variables.bs.js";
import * as ReactNativeSafeAreaView from "react-native-safe-area-view";

var bottomInset = ReactNativeSafeAreaView.getInset("bottom", undefined);

var _BUTTON_HEIGHT = Hero_Variables._HEADER_4 + Hero_Variables._MEDIUM_SIZE * 2.0;

var _BUTTON_BORDER_RADIUS = _BUTTON_HEIGHT * 0.5;

var tmp = {
  color: Hero_Variables._INVERTED_TEXT_COLOR,
  fontSize: Hero_Variables._HEADER_4,
  lineHeight: Hero_Variables._HEADER_4
};

if (Hero_Variables._FONT_FAMILY !== undefined) {
  tmp.fontFamily = Caml_option.valFromOption(Hero_Variables._FONT_FAMILY);
}

var styles = {
  wrapper: {
    backgroundColor: Hero_Variables._PRIMARY_COLOR,
    borderRadius: _BUTTON_BORDER_RADIUS,
    marginHorizontal: Hero_Variables._MEDIUM_SIZE
  },
  wrapperWithoutHomeBar: {
    marginBottom: Hero_Variables._MEDIUM_SIZE,
    paddingBottom: 0.0
  },
  wrapperWithHomeBar: {
    marginBottom: bottomInset,
    paddingBottom: 0.0
  },
  button: {
    alignItems: "center",
    display: "flex",
    height: _BUTTON_HEIGHT,
    justifyContent: "center",
    paddingHorizontal: Hero_Variables._MEDIUM_SIZE
  },
  text: tmp,
  loadingIndicator: {
    color: Hero_Variables._INVERTED_TEXT_COLOR
  },
  disabledWrapper: {
    backgroundColor: Hero_Variables._DISABLED_BACKGROUND_COLOR
  },
  disabledText: {
    color: Hero_Variables._INVERTED_TEXT_COLOR
  }
};

var $$default = ReactNative.StyleSheet.create(styles);

var _GLOBAL_DISABLED_BACKGROUND_COLOR = Hero_Variables._DISABLED_BACKGROUND_COLOR;

var _WRAPPER_MARGIN_HORIZONTAL = Hero_Variables._MEDIUM_SIZE;

var _WRAPPER_NO_HOME_BAR_MARGIN_BOTTOM = Hero_Variables._MEDIUM_SIZE;

var _WRAPPER_NO_HOME_BAR_PADDING_BOTTOM = 0.0;

var _WRAPPER_WITH_HOME_BAR_MARGIN_BOTTOM = bottomInset;

var _WRAPPER_WITH_HOME_BAR_PADDING_BOTTOM = 0.0;

var _TEXT_FONT_SIZE = Hero_Variables._HEADER_4;

var _BUTTON_PADDING_VERTICAL = Hero_Variables._MEDIUM_SIZE;

var _BUTTON_PADDING_HORIZONTAL = Hero_Variables._MEDIUM_SIZE;

var _FILLED_TEXT_COLOR = Hero_Variables._INVERTED_TEXT_COLOR;

var _FILLED_BACKGROUND_COLOR = Hero_Variables._PRIMARY_COLOR;

var _DISABLED_TEXT_COLOR = Hero_Variables._INVERTED_TEXT_COLOR;

var _DISABLED_BACKGROUND_COLOR = Hero_Variables._DISABLED_BACKGROUND_COLOR;

export {
  bottomInset ,
  _GLOBAL_DISABLED_BACKGROUND_COLOR ,
  _WRAPPER_MARGIN_HORIZONTAL ,
  _WRAPPER_NO_HOME_BAR_MARGIN_BOTTOM ,
  _WRAPPER_NO_HOME_BAR_PADDING_BOTTOM ,
  _WRAPPER_WITH_HOME_BAR_MARGIN_BOTTOM ,
  _WRAPPER_WITH_HOME_BAR_PADDING_BOTTOM ,
  _TEXT_FONT_SIZE ,
  _BUTTON_PADDING_VERTICAL ,
  _BUTTON_PADDING_HORIZONTAL ,
  _BUTTON_HEIGHT ,
  _BUTTON_BORDER_RADIUS ,
  _FILLED_TEXT_COLOR ,
  _FILLED_BACKGROUND_COLOR ,
  _DISABLED_TEXT_COLOR ,
  _DISABLED_BACKGROUND_COLOR ,
  styles ,
  $$default ,
  $$default as default,
  
}
/* bottomInset Not a pure module */
