// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as ReactNative from "react-native";
import * as Hero_Variables from "./Hero_Variables.bs.js";

var _WRAPPER_MEDIUM_SIZE = Hero_Variables._LARGE_SIZE * 2.0;

var _WRAPPER_MEDIUM_RADIUS = _WRAPPER_MEDIUM_SIZE / 2.0;

var _WRAPPER_LARGE_SIZE = Hero_Variables._LARGE_SIZE * 4.0;

var _WRAPPER_LARGE_RADIUS = _WRAPPER_LARGE_SIZE / 2.0;

var _TITLE_LARGE_FONT_SIZE = Hero_Variables._HEADER_2 * 2.0;

var tmp = {
  color: Hero_Variables._DARK_PRIMARY_COLOR
};

if (Hero_Variables._FONT_FAMILY !== undefined) {
  tmp.fontFamily = Caml_option.valFromOption(Hero_Variables._FONT_FAMILY);
}

var styles = {
  wrapper: { },
  titleWrapper: {
    borderColor: Hero_Variables._DARK_PRIMARY_COLOR,
    alignItems: "center",
    justifyContent: "center",
    left: 0.0,
    position: "absolute",
    top: 0.0
  },
  title: tmp,
  image: {
    left: 0.0,
    position: "absolute",
    top: 0.0
  },
  mediumWrapper: {
    height: _WRAPPER_MEDIUM_SIZE,
    width: _WRAPPER_MEDIUM_SIZE
  },
  mediumTitleWrapper: {
    borderRadius: _WRAPPER_MEDIUM_RADIUS,
    borderWidth: 1.2,
    height: _WRAPPER_MEDIUM_SIZE,
    width: _WRAPPER_MEDIUM_SIZE
  },
  mediumTitle: {
    fontSize: Hero_Variables._HEADER_2,
    fontWeight: "300"
  },
  mediumImage: {
    borderRadius: _WRAPPER_MEDIUM_RADIUS,
    height: _WRAPPER_MEDIUM_SIZE,
    width: _WRAPPER_MEDIUM_SIZE
  },
  largeWrapper: {
    height: _WRAPPER_LARGE_SIZE,
    width: _WRAPPER_LARGE_SIZE
  },
  largeTitleWrapper: {
    borderRadius: _WRAPPER_LARGE_RADIUS,
    borderWidth: 1.5,
    height: _WRAPPER_LARGE_SIZE,
    width: _WRAPPER_LARGE_SIZE
  },
  largeTitle: {
    fontSize: _TITLE_LARGE_FONT_SIZE,
    fontWeight: "200"
  },
  largeImage: {
    borderRadius: _WRAPPER_LARGE_RADIUS,
    height: _WRAPPER_LARGE_SIZE,
    width: _WRAPPER_LARGE_SIZE
  }
};

var $$default = ReactNative.StyleSheet.create(styles);

var _WRAPPER_BORDER_COLOR = Hero_Variables._DARK_PRIMARY_COLOR;

var _TITLE_COLOR = Hero_Variables._DARK_PRIMARY_COLOR;

var _TITLE_MEDIUM_FONT_SIZE = Hero_Variables._HEADER_2;

var _TITLE_MEDIUM_FONT_WEIGHT = /* _300 */1056055796;

var _TITLE_LARGE_FONT_WEIGHT = /* _200 */1056006067;

export {
  _WRAPPER_BORDER_COLOR ,
  _TITLE_COLOR ,
  _WRAPPER_MEDIUM_SIZE ,
  _WRAPPER_MEDIUM_RADIUS ,
  _TITLE_MEDIUM_FONT_SIZE ,
  _TITLE_MEDIUM_FONT_WEIGHT ,
  _WRAPPER_LARGE_SIZE ,
  _WRAPPER_LARGE_RADIUS ,
  _TITLE_LARGE_FONT_SIZE ,
  _TITLE_LARGE_FONT_WEIGHT ,
  styles ,
  $$default ,
  $$default as default,
  
}
/* default Not a pure module */
