// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as ReactNative from "react-native";
import * as Hero_Variables from "./Hero_Variables.bs.js";

var _THUMB_SIZE = Hero_Variables._BASE_SIZE * 1.5;

var _TRACK_WIDTH = _THUMB_SIZE * 2.0;

var _WRAPPER_WIDTH = _TRACK_WIDTH + 2.0 * 2.0;

var _WRAPPER_HEIGHT = _THUMB_SIZE + 2.0 * 2.0;

var styles = {
  track: {
    borderRadius: _WRAPPER_HEIGHT / 2.0,
    height: _WRAPPER_HEIGHT,
    padding: 2.0,
    width: _WRAPPER_WIDTH
  },
  trackOn: {
    backgroundColor: Hero_Variables._PRIMARY_COLOR
  },
  trackOff: {
    backgroundColor: Hero_Variables._DISABLED_BACKGROUND_COLOR
  },
  thumbWrapper: {
    borderRadius: _THUMB_SIZE / 2.0,
    height: _THUMB_SIZE,
    width: _TRACK_WIDTH
  },
  thumb: {
    backgroundColor: Hero_Variables._WHITE,
    borderRadius: _THUMB_SIZE / 2.0,
    height: _THUMB_SIZE,
    position: "absolute",
    top: 0.0,
    width: _THUMB_SIZE
  },
  thumbOff: {
    left: 0.0
  },
  thumbOn: {
    left: _TRACK_WIDTH - _THUMB_SIZE
  }
};

var $$default = ReactNative.StyleSheet.create(styles);

var _THUMB_COLOR = Hero_Variables._WHITE;

var _TRACK_HEIGHT = _THUMB_SIZE;

var _TRACK_COLOR_ON = Hero_Variables._PRIMARY_COLOR;

var _TRACK_COLOR_OFF = Hero_Variables._DISABLED_BACKGROUND_COLOR;

var _WRAPPER_PADDING = 2.0;

export {
  _THUMB_SIZE ,
  _THUMB_COLOR ,
  _TRACK_WIDTH ,
  _TRACK_HEIGHT ,
  _TRACK_COLOR_ON ,
  _TRACK_COLOR_OFF ,
  _WRAPPER_PADDING ,
  _WRAPPER_WIDTH ,
  _WRAPPER_HEIGHT ,
  styles ,
  $$default ,
  $$default as default,
  
}
/* default Not a pure module */
