// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as ReactNative from "react-native";
import * as Hero_Variables from "./Hero_Variables.bs.js";

var _ACTION_HEIGHT = Hero_Variables._HEADER_5 + Hero_Variables._MEDIUM_SIZE * 2.0;

var styles = {
  wrapper: {
    backgroundColor: Hero_Variables._GREY_5
  },
  actions: {
    borderBottomColor: Hero_Variables._BORDER_COLOR,
    borderBottomWidth: ReactNative.StyleSheet.hairlineWidth,
    flexDirection: "row",
    justifyContent: "flex-end"
  },
  action: {
    height: _ACTION_HEIGHT,
    justifyContent: "center",
    paddingHorizontal: Hero_Variables._MEDIUM_SIZE
  },
  actionText: {
    color: Hero_Variables._LINK_TEXT_COLOR,
    fontSize: Hero_Variables._HEADER_4
  }
};

var $$default = ReactNative.StyleSheet.create(styles);

var _WRAPPER_BACKGROUND_COLOR = Hero_Variables._GREY_5;

var _ACTIONS_BORDER_COLOR = Hero_Variables._BORDER_COLOR;

var _ACTION_TEXT_FONT_SIZE = Hero_Variables._HEADER_4;

var _ACTION_TEXT_LINE_HEIGHT = Hero_Variables._HEADER_5;

var _ACTION_TEXT_COLOR = Hero_Variables._LINK_TEXT_COLOR;

var _ACTION_PADDING_VERTICAL = Hero_Variables._MEDIUM_SIZE;

var _ACTION_PADDING_HORIZONTAL = Hero_Variables._MEDIUM_SIZE;

export {
  _WRAPPER_BACKGROUND_COLOR ,
  _ACTIONS_BORDER_COLOR ,
  _ACTION_TEXT_FONT_SIZE ,
  _ACTION_TEXT_LINE_HEIGHT ,
  _ACTION_TEXT_COLOR ,
  _ACTION_PADDING_VERTICAL ,
  _ACTION_PADDING_HORIZONTAL ,
  _ACTION_HEIGHT ,
  styles ,
  $$default ,
  $$default as default,
  
}
/* styles Not a pure module */
