// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as ReactNative from "react-native";
import * as NormalizeTextJs from "../../helpers/normalizeText.js";

function normalizeText(prim) {
  return NormalizeTextJs.default(prim);
}

var isWeb = ReactNative.Platform.OS === "web";

var _BLUE = "#1dbeee";

var _FOCUS_BLUE_1 = "#003580";

var _RED = "#de350b";

var _BLACK = "#000000";

var _GREY_3 = "#a3a6ac";

var _GREY_4 = "#d9dbdf";

var _WHITE = "#fcfcfc";

var _BASE_SIZE = isWeb ? 16.0 : NormalizeTextJs.default(13.0);

var _FONT_SIZE = isWeb ? 16.0 : NormalizeTextJs.default(13.0);

var _FONT_FAMILY = isWeb ? undefined : "Proxima Nova";

var _SMALL_SIZE = _BASE_SIZE * 0.5;

var _MEDIUM_SIZE = _BASE_SIZE * 1.0;

var _LARGE_SIZE = _BASE_SIZE * 1.5;

var _HEADER_5 = _FONT_SIZE * 0.83;

var _HEADER_4 = _FONT_SIZE * 1.0;

var _HEADER_3 = _FONT_SIZE * 1.17;

var _HEADER_2 = _FONT_SIZE * 1.5;

var _HEADER_1 = _FONT_SIZE * 2.0;

var _FOCUS_BLUE_2 = "#40679f";

var _FOCUS_BLUE_3 = "#5d7ead";

var _BACKGROUND_BLUE_1 = "#347ab7";

var _BACKGROUND_BLUE_2 = "#b5eeff";

var _BACKGROUND_BLUE_3 = "#e6f7ff";

var _ORANGE = "#ffa234";

var _GREY_1 = "#2b2b2b";

var _GREY_2 = "#71767c";

var _GREY_5 = "#f5f6f8";

var _PRIMARY_COLOR = _BLUE;

var _DARK_PRIMARY_COLOR = _FOCUS_BLUE_1;

var _DANGER_COLOR = _RED;

var _TEXT_COLOR = _BLACK;

var _INVERTED_TEXT_COLOR = _WHITE;

var _DISABLED_TEXT_COLOR = _GREY_3;

var _MUTED_TEXT_COLOR = _GREY_3;

var _LINK_TEXT_COLOR = _BLUE;

var _BORDER_COLOR = _GREY_4;

var _BACKGROUND_COLOR = _WHITE;

var _DISABLED_BACKGROUND_COLOR = _GREY_4;

export {
  normalizeText ,
  isWeb ,
  _BLUE ,
  _FOCUS_BLUE_1 ,
  _FOCUS_BLUE_2 ,
  _FOCUS_BLUE_3 ,
  _BACKGROUND_BLUE_1 ,
  _BACKGROUND_BLUE_2 ,
  _BACKGROUND_BLUE_3 ,
  _RED ,
  _ORANGE ,
  _BLACK ,
  _GREY_1 ,
  _GREY_2 ,
  _GREY_3 ,
  _GREY_4 ,
  _GREY_5 ,
  _WHITE ,
  _BASE_SIZE ,
  _FONT_SIZE ,
  _FONT_FAMILY ,
  _PRIMARY_COLOR ,
  _DARK_PRIMARY_COLOR ,
  _DANGER_COLOR ,
  _TEXT_COLOR ,
  _INVERTED_TEXT_COLOR ,
  _DISABLED_TEXT_COLOR ,
  _MUTED_TEXT_COLOR ,
  _LINK_TEXT_COLOR ,
  _BORDER_COLOR ,
  _BACKGROUND_COLOR ,
  _DISABLED_BACKGROUND_COLOR ,
  _SMALL_SIZE ,
  _MEDIUM_SIZE ,
  _LARGE_SIZE ,
  _HEADER_5 ,
  _HEADER_4 ,
  _HEADER_3 ,
  _HEADER_2 ,
  _HEADER_1 ,
  
}
/* isWeb Not a pure module */
