// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as ReactNative from "react-native";
import * as Hero_Variables from "./Hero_Variables.bs.js";

var _INPUT_HEIGHT = Hero_Variables._HEADER_4 + Hero_Variables._MEDIUM_SIZE * 2.0;

var tmp = {
  color: Hero_Variables._MUTED_TEXT_COLOR,
  fontSize: Hero_Variables._HEADER_5,
  fontWeight: "500",
  lineHeight: Hero_Variables._HEADER_5,
  height: Hero_Variables._HEADER_5
};

if (Hero_Variables._FONT_FAMILY !== undefined) {
  tmp.fontFamily = Caml_option.valFromOption(Hero_Variables._FONT_FAMILY);
}

var tmp$1 = {
  color: Hero_Variables._TEXT_COLOR,
  fontSize: Hero_Variables._HEADER_4,
  textAlignVertical: "center",
  flex: 1.0,
  paddingBottom: Hero_Variables._MEDIUM_SIZE,
  paddingTop: Hero_Variables._MEDIUM_SIZE
};

if (Hero_Variables._FONT_FAMILY !== undefined) {
  tmp$1.fontFamily = Caml_option.valFromOption(Hero_Variables._FONT_FAMILY);
}

var tmp$2 = {
  color: Hero_Variables._DANGER_COLOR,
  fontSize: Hero_Variables._HEADER_5,
  fontWeight: "500",
  lineHeight: Hero_Variables._HEADER_5,
  height: Hero_Variables._HEADER_5,
  marginTop: Hero_Variables._SMALL_SIZE
};

if (Hero_Variables._FONT_FAMILY !== undefined) {
  tmp$2.fontFamily = Caml_option.valFromOption(Hero_Variables._FONT_FAMILY);
}

var styles = {
  wrapper: {
    marginBottom: Hero_Variables._MEDIUM_SIZE
  },
  label: tmp,
  textInput: {
    borderBottomColor: Hero_Variables._BORDER_COLOR,
    borderBottomWidth: 0.8,
    alignItems: "center",
    flexDirection: "row"
  },
  baseTextInput: tmp$1,
  icon: {
    color: Hero_Variables._MUTED_TEXT_COLOR,
    height: _INPUT_HEIGHT
  },
  errorMessage: tmp$2,
  errorLabel: {
    color: Hero_Variables._DANGER_COLOR
  },
  errorTextInput: {
    borderBottomColor: Hero_Variables._DANGER_COLOR
  },
  errorIcon: {
    color: Hero_Variables._DANGER_COLOR
  },
  activeLabel: {
    color: Hero_Variables._PRIMARY_COLOR
  },
  activeTextInput: {
    borderBottomColor: Hero_Variables._PRIMARY_COLOR,
    borderBottomWidth: 1.0
  },
  activeIcon: {
    color: Hero_Variables._PRIMARY_COLOR
  },
  disabledBaseTextInput: {
    color: Hero_Variables._DISABLED_TEXT_COLOR
  }
};

var $$default = ReactNative.StyleSheet.create(styles);

var _WRAPPER_MARGIN_VERTICAL = Hero_Variables._MEDIUM_SIZE;

var _LABEL_FONT_SIZE = Hero_Variables._HEADER_5;

var _LABEL_COLOR = Hero_Variables._MUTED_TEXT_COLOR;

var _INPUT_FONT_SIZE = Hero_Variables._HEADER_4;

var _INPUT_PADDING_VERTICAL = Hero_Variables._MEDIUM_SIZE;

var _INPUT_BORDER_COLOR = Hero_Variables._BORDER_COLOR;

var _INPUT_COLOR = Hero_Variables._TEXT_COLOR;

var _ICON_COLOR = Hero_Variables._MUTED_TEXT_COLOR;

var _ERROR_FONT_SIZE = Hero_Variables._HEADER_5;

var _ERROR_MARGIN_VERTICAL = Hero_Variables._SMALL_SIZE;

var _ERROR_COLOR = Hero_Variables._DANGER_COLOR;

var _ACTIVE_COLOR = Hero_Variables._PRIMARY_COLOR;

export {
  _WRAPPER_MARGIN_VERTICAL ,
  _LABEL_FONT_SIZE ,
  _LABEL_COLOR ,
  _INPUT_FONT_SIZE ,
  _INPUT_PADDING_VERTICAL ,
  _INPUT_HEIGHT ,
  _INPUT_BORDER_COLOR ,
  _INPUT_COLOR ,
  _ICON_COLOR ,
  _ERROR_FONT_SIZE ,
  _ERROR_MARGIN_VERTICAL ,
  _ERROR_COLOR ,
  _ACTIVE_COLOR ,
  styles ,
  $$default ,
  $$default as default,
  
}
/* default Not a pure module */
