// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as ReactNative from "react-native";
import * as Hero_Variables from "./Hero_Variables.bs.js";

var styles = {
  icon: {
    color: Hero_Variables._TEXT_COLOR
  }
};

var $$default = ReactNative.StyleSheet.create(styles);

var _COLOR = Hero_Variables._TEXT_COLOR;

export {
  _COLOR ,
  styles ,
  $$default ,
  $$default as default,
  
}
/* default Not a pure module */
