// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Hero_Icon from "./Hero_Icon.bs.js";
import * as Hero_Text from "./Hero_Text.bs.js";
import * as Hero_Avatar from "./Hero_Avatar.bs.js";
import * as Hero_Button from "./Hero_Button.bs.js";
import * as Hero_Switch from "./Hero_Switch.bs.js";
import * as Hero_ListItem from "./Hero_ListItem.bs.js";
import * as Hero_TextInput from "./Hero_TextInput.bs.js";
import * as Hero_DateTimePicker from "./Hero_DateTimePicker.bs.js";

var $$default = {
  button: Hero_Button.$$default,
  text: Hero_Text.$$default,
  listItem: Hero_ListItem.$$default,
  textInput: Hero_TextInput.$$default,
  icon: Hero_Icon.$$default,
  _switch: Hero_Switch.$$default,
  avatar: Hero_Avatar.$$default,
  dateTimePicker: Hero_DateTimePicker.$$default
};

export {
  $$default ,
  $$default as default,
  
}
/* Hero_Icon Not a pure module */
