// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as ReactNative from "react-native";
import * as Hero_Variables from "./Hero_Variables.bs.js";

var _TITLE_LINE_HEIGHT = Hero_Variables._HEADER_4 * 1.4;

var _SUBTITLE_LINE_HEIGHT = Hero_Variables._HEADER_5 * 1.4;

var _WRAPPER_HEIGHT = _TITLE_LINE_HEIGHT + _SUBTITLE_LINE_HEIGHT + Hero_Variables._MEDIUM_SIZE * 2.0;

var tmp = {
  color: Hero_Variables._TEXT_COLOR,
  fontSize: Hero_Variables._HEADER_4,
  fontWeight: "500",
  lineHeight: _TITLE_LINE_HEIGHT
};

if (Hero_Variables._FONT_FAMILY !== undefined) {
  tmp.fontFamily = Caml_option.valFromOption(Hero_Variables._FONT_FAMILY);
}

var tmp$1 = {
  color: Hero_Variables._MUTED_TEXT_COLOR,
  fontSize: Hero_Variables._HEADER_5,
  fontWeight: "500",
  lineHeight: _SUBTITLE_LINE_HEIGHT
};

if (Hero_Variables._FONT_FAMILY !== undefined) {
  tmp$1.fontFamily = Caml_option.valFromOption(Hero_Variables._FONT_FAMILY);
}

var styles = {
  wrapper: {
    borderBottomColor: Hero_Variables._BORDER_COLOR,
    borderBottomWidth: 0.8,
    alignItems: "center",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: _WRAPPER_HEIGHT,
    paddingHorizontal: Hero_Variables._MEDIUM_SIZE,
    paddingVertical: Hero_Variables._MEDIUM_SIZE
  },
  title: tmp,
  subtitle: tmp$1,
  contentWrapper: {
    alignItems: "center",
    flexDirection: "row"
  }
};

var $$default = {
  styles: ReactNative.StyleSheet.create(styles)
};

var _TITLE_FONT_SIZE = Hero_Variables._HEADER_4;

var _TITLE_COLOR = Hero_Variables._TEXT_COLOR;

var _SUBTITLE_FONT_SIZE = Hero_Variables._HEADER_5;

var _SUBTITLE_COLOR = Hero_Variables._MUTED_TEXT_COLOR;

var _WRAPPER_PADDING_VERTICAL = Hero_Variables._MEDIUM_SIZE;

var _WRAPPER_PADDING_HORIZONTAL = Hero_Variables._MEDIUM_SIZE;

var _WRAPPER_BORDER_COLOR = Hero_Variables._BORDER_COLOR;

export {
  _TITLE_FONT_SIZE ,
  _TITLE_LINE_HEIGHT ,
  _TITLE_COLOR ,
  _SUBTITLE_FONT_SIZE ,
  _SUBTITLE_LINE_HEIGHT ,
  _SUBTITLE_COLOR ,
  _WRAPPER_PADDING_VERTICAL ,
  _WRAPPER_PADDING_HORIZONTAL ,
  _WRAPPER_HEIGHT ,
  _WRAPPER_BORDER_COLOR ,
  styles ,
  $$default ,
  $$default as default,
  
}
/* default Not a pure module */
