let default = {
  "variables": Hero_Variables.default,
  "button": Hero_Button.default,
  "text": Hero_Text.default,
  "listItem": Hero_ListItem.default,
  "textInput": Hero_TextInput.default,
  "icon": Hero_Icon.default,
  "_switch": Hero_Switch.default,
  "avatar": Hero_Avatar.default,
  "bottomButton": Hero_BottomButton.default,
  "dateTimePicker": Hero_DateTimePicker.default,
  "tabBar": Hero_TabBar.default,
  "card": Hero_Card.default,
  "container": Hero_Container.default,
};
